server:
  port: 8080
services:
  url:
    user-service: ${USER_SERVICE_URL:http://user-service:8081}
    task-service: ${TASK_SERVICE_URL:http://task-service:8082}
    comment-service: ${COMMENT_SERVICE_URL:http://comment-service:8083}
    notification-service: ${NOTIFICATION_SERVICE_URL:http://notification-service:8084}
    auth-service: ${AUTH_SERVICE_URL:http://authentication-service:8085}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0]:
        id: auth-service
        uri: ${services.url.auth-service}
        predicates:
          - Path=/auths/api/**
        filters:
          - name: CircuitBreaker
            args:
              name: Auth Service
              fallbackUri: forward:/error
      routes[1]:
        id: user-service
        uri: ${services.url.user-service}
        predicates:
          - Path=/users/api/**
        filters:
          - name: CircuitBreaker
            args:
              name: User Service
              fallbackUri: forward:/error
      routes[2]:
        id: task-service
        uri: ${services.url.task-service}
        predicates:
          - Path=/tasks/api/**
        filters:
          - name: CircuitBreaker
            args:
              name: Task Service
              fallbackUri: forward:/error
      routes[3]:
        id: comment-service
        uri: ${services.url.comment-service}
        predicates:
          - Path=/comments/api/**
        filters:
          - name: CircuitBreaker
            args:
              name: Comment Service
              fallbackUri: forward:/error
      routes[4]:
        id: notification-service
        uri: ${services.url.notification-service}
        predicates:
          - Path=/notifications/api/**
        filters:
          - name: CircuitBreaker
            args:
              name: Notification Service
              fallbackUri: forward:/error
  main:
    web-application-type: reactive
jwt:
  secret: ENk2InMhEpe50LtIdvnjbjE0Ia0virEr9wCJJ6UAms

