server:
  port: 8085

spring:
  application:
    name: auth-service

user-service:
  base-url: http://localhost:8081

jwt:
  secret: ENk2InMhEpe50LtIdvnjbjE0Ia0virEr9wCJJ6UAms
  issuer: "management-system"
  expiration: 864000
  refresh-token:
    expiration: 604800000
