server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
